moddef::moddef!(
    flat(pub) mod {
        array_chunks,
        chain,
        cloned,
        copied,
        empty,
        contained,
        inspect,
        intersperse,
        map,
        mutate,
        once_with,
        once,
        repeat_n,
        rev,
        step_by,
        take,
        zip
    }
);